"""Branded PDF generation for valuations and market briefs (ReportLab)."""
import io
from datetime import datetime

from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_LEFT, TA_RIGHT
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle,
    HRFlowable, ListFlowable, ListItem,
)

NAVY = colors.HexColor("#0F172A")
SKY = colors.HexColor("#0284C7")
EMER = colors.HexColor("#059669")
ROSE = colors.HexColor("#E11D48")
AMBER = colors.HexColor("#B45309")
SLATE = colors.HexColor("#475569")
MUTED = colors.HexColor("#94A3B8")
LINE = colors.HexColor("#E2E8F0")
PANEL = colors.HexColor("#F1F5F9")

_SS = getSampleStyleSheet()


def _style(name, **kw):
    base = kw.pop("parent", _SS["Normal"])
    return ParagraphStyle(name, parent=base, **kw)


H1 = _style("H1", fontName="Helvetica-Bold", fontSize=20, leading=24, textColor=NAVY, spaceAfter=2)
SUB = _style("SUB", fontName="Helvetica", fontSize=10, leading=14, textColor=SLATE, spaceAfter=2)
META = _style("META", fontName="Helvetica", fontSize=8.5, leading=12, textColor=MUTED)
LABEL = _style("LABEL", fontName="Helvetica-Bold", fontSize=8.5, leading=12, textColor=SKY)
SECTION = _style("SECTION", fontName="Helvetica-Bold", fontSize=11, leading=14, textColor=NAVY, spaceBefore=10, spaceAfter=4)
BODY = _style("BODY", fontName="Helvetica", fontSize=10, leading=15, textColor=colors.HexColor("#1E293B"))
ITALIC = _style("ITALIC", fontName="Helvetica-Oblique", fontSize=9, leading=13, textColor=SLATE)
BULLET = _style("BULLET", fontName="Helvetica", fontSize=9.5, leading=14, textColor=colors.HexColor("#1E293B"))
METRIC_LABEL = _style("ML", fontName="Helvetica", fontSize=8, leading=10, textColor=MUTED)
METRIC_VAL = _style("MV", fontName="Helvetica-Bold", fontSize=15, leading=18, textColor=NAVY)


def _rating_color(r):
    return {"Buy": EMER, "Sell": ROSE}.get(r, AMBER)


def _fmt(n, d=2):
    try:
        return f"{float(n):,.{d}f}"
    except (TypeError, ValueError):
        return "—"


def _fmt_date(iso):
    try:
        return datetime.fromisoformat(iso.replace("Z", "+00:00")).strftime("%d %b %Y, %H:%M UTC")
    except Exception:
        return datetime.utcnow().strftime("%d %b %Y UTC")


def _header_footer(canvas, doc):
    canvas.saveState()
    w, h = A4
    # Brand bar
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - 16 * mm, w, 16 * mm, fill=1, stroke=0)
    canvas.setFillColor(SKY)
    canvas.setFont("Helvetica-Bold", 13)
    canvas.drawString(18 * mm, h - 11 * mm, "ĀRTHA AI")
    canvas.setFillColor(colors.white)
    canvas.setFont("Helvetica", 8)
    canvas.drawString(37 * mm, h - 11 * mm, "·  INVESTMENT INTELLIGENCE PLATFORM")
    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 7.5)
    canvas.drawRightString(w - 18 * mm, h - 11 * mm, "Confidential — Research Desk")
    # Footer
    canvas.setStrokeColor(LINE)
    canvas.setLineWidth(0.5)
    canvas.line(18 * mm, 15 * mm, w - 18 * mm, 15 * mm)
    canvas.setFillColor(MUTED)
    canvas.setFont("Helvetica", 7)
    canvas.drawString(18 * mm, 10 * mm,
                      "For professional/institutional use only. Not investment advice. "
                      "Generated by Artha AI. Market data may include simulated values.")
    canvas.drawRightString(w - 18 * mm, 10 * mm, f"Page {doc.page}")
    canvas.restoreState()


def _doc(buf):
    return SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=18 * mm, rightMargin=18 * mm,
        topMargin=22 * mm, bottomMargin=20 * mm,
        title="Artha AI Report",
    )


def _metric_box(label, value, color=NAVY):
    t = Table([[Paragraph(label, METRIC_LABEL)], [Paragraph(value, _style("mv", parent=METRIC_VAL, textColor=color))]],
              colWidths=[52 * mm])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), PANEL),
        ("BOX", (0, 0), (-1, -1), 0.5, LINE),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (0, 0), 7),
        ("BOTTOMPADDING", (0, -1), (-1, -1), 7),
    ]))
    return t


def _bullets(items, color=SKY):
    if not items:
        return Paragraph("—", BODY)
    return ListFlowable(
        [ListItem(Paragraph(str(i), BULLET), bulletColor=color, value="square") for i in items],
        bulletType="bullet", leftIndent=10, bulletFontSize=6,
    )


def valuation_pdf(v: dict) -> bytes:
    buf = io.BytesIO()
    doc = _doc(buf)
    story = []

    story.append(Paragraph(f"{v.get('name', '')}", H1))
    story.append(Paragraph(f"{v.get('ticker', '')} &nbsp;·&nbsp; AI Valuation Check", SUB))
    story.append(Paragraph(
        f"Generated {_fmt_date(v.get('generatedAt', ''))} &nbsp;·&nbsp; Engine: {v.get('engine', '—')}", META))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1, color=LINE))
    story.append(Spacer(1, 10))

    rating = v.get("rating", "Hold")
    rc = _rating_color(rating)
    rating_tbl = Table([[
        Paragraph(f'<font color="#FFFFFF"><b>{rating.upper()}</b></font>', _style("r", fontName="Helvetica-Bold", fontSize=12, alignment=TA_LEFT)),
        Paragraph(f"Confidence: <b>{v.get('confidence', '—')}</b>", _style("c", fontSize=9, textColor=SLATE, alignment=TA_RIGHT)),
    ]], colWidths=[40 * mm, 123 * mm])
    rating_tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (0, 0), rc),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (0, 0), 10), ("RIGHTPADDING", (0, 0), (0, 0), 10),
        ("TOPPADDING", (0, 0), (-1, -1), 6), ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(rating_tbl)
    story.append(Spacer(1, 10))

    cur = v.get("currency", "")
    upside = v.get("upsidePct")
    up_color = EMER if (isinstance(upside, (int, float)) and upside > 0) else ROSE if (isinstance(upside, (int, float)) and upside < 0) else SLATE
    metrics = Table([[
        _metric_box("CURRENT PRICE", f"{cur} {_fmt(v.get('price'))}"),
        _metric_box("FAIR VALUE", f"{cur} {_fmt(v.get('fairValue'))}", SKY),
        _metric_box("UPSIDE", f"{'+' if isinstance(upside,(int,float)) and upside>0 else ''}{_fmt(upside)}%", up_color),
    ]], colWidths=[54 * mm, 54 * mm, 54 * mm])
    metrics.setStyle(TableStyle([("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 4)]))
    story.append(metrics)
    story.append(Spacer(1, 6))

    story.append(Paragraph("Investment Thesis", SECTION))
    story.append(Paragraph(v.get("thesis", "—"), BODY))
    if v.get("valuationNote"):
        story.append(Spacer(1, 3))
        story.append(Paragraph(v["valuationNote"], ITALIC))

    bull = Table([[Paragraph('<font color="#059669">Bull Case</font>', SECTION)], [_bullets(v.get("bullCase"), EMER)]], colWidths=[79 * mm])
    bear = Table([[Paragraph('<font color="#E11D48">Bear Case</font>', SECTION)], [_bullets(v.get("bearCase"), ROSE)]], colWidths=[79 * mm])
    bb = Table([[bull, bear]], colWidths=[82 * mm, 82 * mm])
    bb.setStyle(TableStyle([("VALIGN", (0, 0), (-1, -1), "TOP"), ("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (0, 0), 6)]))
    story.append(bb)

    story.append(Paragraph('<font color="#B45309">Key Risks</font>', SECTION))
    story.append(_bullets(v.get("keyRisks"), AMBER))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()


def market_brief_pdf(d: dict) -> bytes:
    buf = io.BytesIO()
    doc = _doc(buf)
    story = []
    m = d.get("movers", {})

    story.append(Paragraph("Market Intelligence Brief", H1))
    story.append(Paragraph(d.get("headline", ""), SUB))
    story.append(Paragraph(
        f"Generated {_fmt_date(d.get('generatedAt', ''))} &nbsp;·&nbsp; Engine: {d.get('engine', '—')}", META))
    story.append(Spacer(1, 6))
    story.append(HRFlowable(width="100%", thickness=1, color=LINE))
    story.append(Spacer(1, 10))

    sentiment = m.get("sentiment", "—")
    s_color = EMER if sentiment == "Risk-On" else ROSE if sentiment == "Risk-Off" else AMBER
    stats = Table([[
        _metric_box("REGIME", sentiment, s_color),
        _metric_box("BREADTH", f"{_fmt(m.get('breadth'), 1)}%", SKY),
        _metric_box("ADV / DEC", f"{m.get('advancers', 0)} / {m.get('decliners', 0)}"),
    ]], colWidths=[54 * mm, 54 * mm, 54 * mm])
    stats.setStyle(TableStyle([("LEFTPADDING", (0, 0), (-1, -1), 0), ("RIGHTPADDING", (0, 0), (-1, -1), 4)]))
    story.append(stats)
    story.append(Spacer(1, 6))

    story.append(Paragraph("Summary", SECTION))
    story.append(Paragraph(d.get("summary", "—"), BODY))

    if d.get("themes"):
        story.append(Paragraph("Key Themes", SECTION))
        for t in d["themes"]:
            story.append(Paragraph(f"<b>{t.get('title', '')}</b> — {t.get('detail', '')}", BODY))
            story.append(Spacer(1, 2))

    if d.get("watchItems"):
        story.append(Paragraph("On the Watch", SECTION))
        story.append(_bullets(d["watchItems"], SKY))

    def mover_rows(rows):
        data = [["Ticker", "Security", "Price", "Day %"]]
        for s in rows:
            data.append([s.get("ticker", ""), s.get("name", ""), _fmt(s.get("price")), f"{'+' if s.get('changePct',0)>0 else ''}{_fmt(s.get('changePct'))}%"])
        return data

    if m.get("gainers") or m.get("losers"):
        story.append(Paragraph("Market Movers", SECTION))
        for title, rows, col in [("Top Gainers", m.get("gainers", []), EMER), ("Top Losers", m.get("losers", []), ROSE)]:
            story.append(Paragraph(f'<font color="#{col.hexval()[2:8]}"><b>{title}</b></font>', _style("mt", fontSize=9, spaceBefore=4, spaceAfter=2)))
            tbl = Table(mover_rows(rows), colWidths=[26 * mm, 80 * mm, 28 * mm, 30 * mm])
            tbl.setStyle(TableStyle([
                ("BACKGROUND", (0, 0), (-1, 0), PANEL),
                ("TEXTCOLOR", (0, 0), (-1, 0), SLATE),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
                ("TEXTCOLOR", (0, 1), (0, -1), SKY),
                ("ALIGN", (2, 0), (-1, -1), "RIGHT"),
                ("LINEBELOW", (0, 0), (-1, -1), 0.4, LINE),
                ("TOPPADDING", (0, 0), (-1, -1), 4), ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
            ]))
            story.append(tbl)
            story.append(Spacer(1, 4))

    doc.build(story, onFirstPage=_header_footer, onLaterPages=_header_footer)
    return buf.getvalue()
