import React from "react";
import { useQuery } from "@tanstack/react-query";
import { motion } from "framer-motion";
import { Sparkles, TrendingUp, TrendingDown, Eye, Gauge, FileDown } from "lucide-react";
import { fetchers, pdfUrls, downloadFile } from "../lib/api";
import { fmtNum, fmtPct, changeColor } from "../lib/format";
import { Card, SectionLabel, Spinner, ViewHeader, Pill, statusTone } from "../components/ui-kit";

export default function InsightsView() {
  const { data, isLoading } = useQuery({
    queryKey: ["insights"],
    queryFn: fetchers.insights,
    refetchInterval: 30000,
  });

  if (isLoading || !data) return <Spinner label="Generating market brief" />;

  const m = data.movers;
  const sentimentTone = m.sentiment === "Risk-On" ? "bull" : m.sentiment === "Risk-Off" ? "bear" : "warn";

  return (
    <div>
      <ViewHeader
        eyebrow="AI Research Desk"
        title="Market Intelligence Feed"
        desc="Live quantitative breadth paired with an AI-generated research-desk brief. Commentary is produced by Claude Sonnet from the current session's market data."
      />

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
        {/* AI brief */}
        <Card className="lg:col-span-8 p-6" data-testid="ai-market-brief">
          <div className="flex items-center justify-between">
            <SectionLabel className="flex items-center gap-1.5 text-sky-400">
              <Sparkles className="w-3.5 h-3.5" /> AI Market Brief
            </SectionLabel>
            <div className="flex items-center gap-2">
              <button
                data-testid="insights-export-pdf-button"
                onClick={() => downloadFile(pdfUrls.insights())}
                className="flex items-center gap-1.5 surface-2 border-hair hover:border-sky-500/40 text-muted-2 hover:text-[var(--text)] text-xs font-medium px-3 py-1.5 rounded-full transition-colors duration-150"
              >
                <FileDown className="w-3.5 h-3.5" /> Export PDF
              </button>
              <Pill tone={sentimentTone}>{m.sentiment}</Pill>
            </div>
          </div>
          <h2 className="font-heading text-2xl font-semibold tracking-tight mt-3">{data.headline}</h2>
          <p className="text-muted-2 text-sm leading-relaxed mt-3">{data.summary}</p>
          {data.engine && (
            <p className="text-[11px] text-muted-3 mt-2 font-mono">Generated by {data.engine}</p>
          )}

          {data.themes?.length > 0 && (
            <div className="grid sm:grid-cols-3 gap-4 mt-6">
              {data.themes.map((t, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, y: 10 }}
                  animate={{ opacity: 1, y: 0 }}
                  transition={{ delay: i * 0.08 }}
                  className="surface-2 border-hair rounded-lg p-4"
                >
                  <p className="font-heading font-semibold text-sm">{t.title}</p>
                  <p className="text-muted-2 text-xs leading-relaxed mt-1.5">{t.detail}</p>
                </motion.div>
              ))}
            </div>
          )}
        </Card>

        {/* Breadth + watch */}
        <div className="lg:col-span-4 space-y-6">
          <Card className="p-6">
            <SectionLabel className="flex items-center gap-1.5"><Gauge className="w-3.5 h-3.5" /> Market Breadth</SectionLabel>
            <div className="mt-4">
              <div className="flex items-end justify-between">
                <p className="font-mono text-3xl font-semibold">{fmtNum(m.breadth, 1)}%</p>
                <p className="text-xs text-muted-3 mb-1">advancing</p>
              </div>
              <div className="w-full h-2 rounded-full surface-2 mt-3 overflow-hidden">
                <motion.div
                  className="h-full bg-emerald-400"
                  initial={{ width: 0 }}
                  animate={{ width: `${m.breadth}%` }}
                  transition={{ duration: 0.6 }}
                />
              </div>
              <div className="flex justify-between text-xs mt-2">
                <span className="text-emerald-400 font-mono">{m.advancers} ▲</span>
                <span className="text-rose-400 font-mono">{m.decliners} ▼</span>
              </div>
            </div>
          </Card>

          <Card className="p-6">
            <SectionLabel className="flex items-center gap-1.5"><Eye className="w-3.5 h-3.5" /> On the Watch</SectionLabel>
            <ul className="mt-3 space-y-2.5">
              {(data.watchItems || []).map((w, i) => (
                <li key={i} className="flex gap-2 text-sm text-muted-2">
                  <span className="text-sky-400 mt-0.5">→</span> {w}
                </li>
              ))}
            </ul>
          </Card>
        </div>
      </div>

      {/* Movers */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6 mt-6">
        <MoverList title="Top Gainers" icon={TrendingUp} tone="text-emerald-400" rows={m.gainers} testid="movers-gainers" />
        <MoverList title="Top Losers" icon={TrendingDown} tone="text-rose-400" rows={m.losers} testid="movers-losers" />
      </div>
    </div>
  );
}

const MoverList = ({ title, icon: Icon, tone, rows, testid }) => (
  <Card className="p-0 overflow-hidden" data-testid={testid}>
    <div className="px-6 py-4 border-b border-hair">
      <SectionLabel className={`flex items-center gap-1.5 ${tone}`}>
        <Icon className="w-3.5 h-3.5" /> {title}
      </SectionLabel>
    </div>
    <div className="divide-y divide-[var(--border)]">
      {rows.map((s) => (
        <div key={s.ticker} className="px-6 py-3 flex items-center justify-between hover:bg-sky-500/[0.04] transition-colors duration-150">
          <div>
            <p className="font-mono text-xs text-sky-400">{s.ticker}</p>
            <p className="text-xs text-muted-2 mt-0.5 max-w-[180px] truncate">{s.name}</p>
          </div>
          <div className="text-right">
            <p className="font-mono text-xs">{fmtNum(s.price)}</p>
            <p className={`font-mono text-xs mt-0.5 ${changeColor(s.changePct)}`}>{fmtPct(s.changePct)}</p>
          </div>
        </div>
      ))}
    </div>
  </Card>
);
